[package]
name = "CVE-2018-1932X"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.39.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO"
]